apiVersion: batch/v1
kind: Job
metadata:
  name: map-matcher-job
spec:
  template:
    metadata:
      labels:
        app: map-matcher
    spec:
      containers:
      - name: map-matcher
        image: ethanyager/map-matcher:latest
        imagePullPolicy: Never
        env:
          - name: PULSAR_SERVICE_URL
            value: "pulsar://pulsar-service:6650"
          - name: POSTGRES_CONN
            value: "dbname=mapmatcher user=postgres password=postgres host=postgres-service port=5432"
          - name: PULSAR_TOPIC
            value: "gps-events"
      restartPolicy: Never
  backoffLimit: 4