apiVersion: v1
kind: Service
metadata:
  name: pulsar-service
spec:
  type: NodePort
  ports:
    - name: broker
      port: 6650
      targetPort: 6650
      nodePort: 30001
    - name: admin
      port: 8080
      targetPort: 8080
  selector:
    app: pulsar